
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "INPUT INT PRINT STR id strProgram : Declarations StatementsDeclarations : Declarations DeclarationDeclarations : Declaration : Type IdListType : INTIdList : IdList ',' idIdList : idStatements : Statements StatementStatements : StatementStatement : id '=' ExpStatement : PRINT '(' PrintArgs ')' PrintArgs : PrintArgs ','  PrintArgPrintArgs : PrintArgPrintArg : idPrintArg : strPrintArg : ExpExp : INT '(' Exp ')'Exp : INPUT '(' str ')'"
    
_lr_action_items = {'id':([0,2,3,4,5,6,9,10,11,12,14,15,16,24,27,28,32,33,],[-3,7,7,-2,-9,12,-5,-8,-4,-7,21,24,-10,-6,-11,21,-17,-18,]),'PRINT':([0,2,3,4,5,10,11,12,16,24,27,32,33,],[-3,8,8,-2,-9,-8,-4,-7,-10,-6,-11,-17,-18,]),'INT':([0,2,4,11,12,13,14,24,25,28,],[-3,9,-2,-4,-7,17,17,-6,17,17,]),'$end':([1,3,5,10,16,27,32,33,],[0,-1,-9,-8,-10,-11,-17,-18,]),'=':([7,],[13,]),'(':([8,17,18,],[14,25,26,]),',':([11,12,19,20,21,22,23,24,31,32,33,],[15,-7,28,-13,-14,-15,-16,-6,-12,-17,-18,]),'INPUT':([13,14,25,28,],[18,18,18,18,]),'str':([14,26,28,],[22,30,22,]),')':([19,20,21,22,23,29,30,31,32,33,],[27,-13,-14,-15,-16,32,33,-12,-17,-18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Program':([0,],[1,]),'Declarations':([0,],[2,]),'Statements':([2,],[3,]),'Declaration':([2,],[4,]),'Statement':([2,3,],[5,10,]),'Type':([2,],[6,]),'IdList':([6,],[11,]),'Exp':([13,14,25,28,],[16,23,29,23,]),'PrintArgs':([14,],[19,]),'PrintArg':([14,28,],[20,31,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Program","S'",1,None,None,None),
  ('Program -> Declarations Statements','Program',2,'p_Program','programas_sin.py',7),
  ('Declarations -> Declarations Declaration','Declarations',2,'p_Declarations_list','programas_sin.py',10),
  ('Declarations -> <empty>','Declarations',0,'p_Declarations_empty','programas_sin.py',13),
  ('Declaration -> Type IdList','Declaration',2,'p_Declaration','programas_sin.py',16),
  ('Type -> INT','Type',1,'p_Type_int','programas_sin.py',19),
  ('IdList -> IdList , id','IdList',3,'p_IdList_str','programas_sin.py',22),
  ('IdList -> id','IdList',1,'p_IdList_single','programas_sin.py',25),
  ('Statements -> Statements Statement','Statements',2,'p_Statements_list','programas_sin.py',28),
  ('Statements -> Statement','Statements',1,'p_Statements_single','programas_sin.py',31),
  ('Statement -> id = Exp','Statement',3,'p_Statement_atrib','programas_sin.py',34),
  ('Statement -> PRINT ( PrintArgs )','Statement',4,'p_Statement_print','programas_sin.py',37),
  ('PrintArgs -> PrintArgs , PrintArg','PrintArgs',3,'p_PrintArgs_list','programas_sin.py',40),
  ('PrintArgs -> PrintArg','PrintArgs',1,'p_PrintArgs_single','programas_sin.py',43),
  ('PrintArg -> id','PrintArg',1,'p_PrintArg_id','programas_sin.py',46),
  ('PrintArg -> str','PrintArg',1,'p_PrintArg_str','programas_sin.py',49),
  ('PrintArg -> Exp','PrintArg',1,'p_PrintArg_Exp','programas_sin.py',52),
  ('Exp -> INT ( Exp )','Exp',4,'p_Exp_int','programas_sin.py',55),
  ('Exp -> INPUT ( str )','Exp',4,'p_Exp_input','programas_sin.py',58),
]
