#+TITLE: Teste 2014 15

*  Grupo 1
a) Caracterize e explique as decisões tomadas ao nível da representação do conhecimento;

  #+begin_src prolog
  aluno :: Id, Nome, Curso, Ano, Ects, Propina -> {V,F}

  id :: Id -> {V,F}
  nome :: Nome -> {V,F,Desconhecido}
  curso :: Curso -> {V,F,Desconhecido}
  ano :: Ano -> {V,F,Desconhecido}
  ects :: Ects -> {V,F,Desconhecido}
  propina :: Propina -> {V,F,Desconhecido}
  #+end_src

  Um aluno é caracterizado por ter :
   - um id
   - nome
   - frequentar um curso
   - andar num certo ano
   - ter ECTS
   - algo que identifique se ele já pagou a propina

b) Conhecimento

   + Definir o conhecimento falso
        #+begin_src prolog :noweb yes
-aluno(Id,N,C,A,E,P):-
    not(aluno(Id,N,C,A,E,P)),
    not(exception(aluno(Id,N,C,A,E,P))).
        #+end_src

   + Valores nulos do tipo interdito

        #+begin_src prolog :noweb yes
nulo(interdito).
        #+end_src

   + Excepcoes
         #+begin_src prolog :noweb yes
 exception(aluno(I,_,C,A,E,P)):- aluno(I,nulo,C,A,E,P).
 exception(aluno(I,_,C,A,E,P)):- aluno(I,nulo,C,A,E,P).
 exception(aluno(I,N,_,A,E,P)):- aluno(I,N,nulo,A,E,P).
 exception(aluno(I,N,_,A,E,P)):- aluno(I,N,incerto,A,E,P).
 exception(aluno(I,N,_,A,E,P)):- aluno(I,N,interdito,A,E,P).
 exception(aluno(I,N,C,_,E,P)):- aluno(I,N,C,incerto,E,P).
 exception(aluno(I,N,C,A,_,P)):- aluno(I,N,C,A,incerto,P).
 exception(aluno(I,N,C,A,_,P)):- aluno(I,N,C,A,nulo,P).
 exception(aluno(I,N,C,A,E,_)):- aluno(I,N,C,A,E,incerto).
 exception(aluno(3456,carlos,mdi,1,Ects,sim)):-
     Ects < 45, (-1) < Ects .
 exception(aluno(45678,duarte,miec,A,180,sim)):-
     A < 6, 2 < A.
 exception(aluno(67890,filipe,C,1,E,nao)):-
     ( C == lfis ; C == lefis ),
     ( E == 45 ; E == 54).
 exception(aluno(78901,N,lcc,3,180,sim)):-
     N == gisela ; N == gisele; N == gabriel.
     #+end_src

   + Conhecimento

        #+begin_src prolog :noweb yes
aluno(12345,ana,lei,1,60,sim).
aluno(23456,beatriz,lcc,2,60,nao).
aluno(56789,eva,miec,4,240,incerto).
aluno(89012,heitor,interdito,1,10,nao).
aluno(90123,ivo,incerto,2,180,sim).
        #+end_src

c) Invariantes
    #+begin_src prolog :noweb yes
+aluno(_,_,_,_,_,_):: (
     findall(Id, (aluno(Id,_,_,A,E,_), (A > 5 ; E > 300)), S ),
     length(S,0)).

+aluno(89012,_,_,_,_,_)::(
     findall(A, (aluno(89012,A,X,_,_,_), not(nulo(X))), R),
     length(R,0)
 ).
    #+end_src
d) Inserir conhecimento
  #+begin_src prolog
%% validar conhecimento
valid([]).
valid([A|T]):- A, valid(T).

%% Inserir conhecimento
inserir(New):- assert(New).
inserir(New):- retract(New), !, fail.

%% Adicionar um novo predicado obedecendo os invariantes
new_predicado(New):-
    findall(X,New::+X,S),
    inserir(New),
    valid(S).

%% Adicionar um novo aluno
add_aluno(Id,N,C,A,E,P):- new_predicado(aluno(Id,N,C,A,E,P)).
  #+end_src
** Questao 2
#+begin_src prolog
si(Questao,verdadeiro):- Questao.
si(Questao,falso):- -Questao.
si(Questao,desconhecido):- not(Questao), not(-Questao).
%- - - - - - - - - - - - - - - - - - - - - - - - - - -  -  -  -  -   -
% Extensao do predicado queryConjuncao: [Questao],Resposta -> {V,F,D}
% capaz de fazer a conjunção de uma lista de questões
% produzindo um resultado final
queryConjuncao([],R).
queryConjuncao([Q],R) :- si(Q,R).
queryConjuncao([Q|Qs], R) :- si(Q, R1), queryConjuncao(Qs,R2), conjuncao(R1,R2,R).

% Extensao do predicado queryDisjuncao: [Questao],Resposta -> {V,F,D}
% capaz de fazer a disjunção de uma lista de questões
% produzindo um resultado final
queryDisjuncao([],R).
queryDisjuncao([Q],R) :- si(Q,R).
queryDisjuncao([Q|Qs], R) :- si(Q, R1), queryDisjuncao(Qs,R2), disjuncao(R1,R2,R).

%- - - - - - - - - - - - - - - - - - - - - - - - - - -  -  -  -  -   -
% Extensao do predicado query: (Operador, Questao1, Questao2),Resposta -> {V,F,D}
% capaz de fazer a conjunção ou a disjunção de duas questões
% produzindo um resultado final
query(('OR',Q1,Q2),R) :- query(Q1,R1), query(Q2,R2), disjuncao(R1,R2,R).
query(('AND',Q1,Q2),R) :- query(Q1,R1), query(Q2,R2), conjuncao(R1,R2,R).
query(Q,R) :- si(Q,R).

%- - - - - - - - - - - - - - - - - - - - - - - - - - -  -  -  -  -   -
% Extensao do meta-predicado queries: [Questao], Resposta -> {V,F,D}
% capaz de fazer a conjunção e/ou disjunção de uma lista de questões
% produzindo um resultado final
queries([],verdadeiro).
queries([Q],R) :- si(Q,R).
queries([Q1,'AND'|Qs],R) :- si(Q1,R1),
                            queries(Qs,R2),
                            conjuncao(R1,R2,R).
queries([Q1,'OR'|Qs],R) :- si(Q1,R1),
                           queries(Qs,R2),
                           disjuncao(R1,R2,R).

%- - - - - - - - - - - - - - - - - - - - - - - - - - -  -  -  -  -   -
% Extensao do predicado conjuncao: X,Y -> {V,F,D}
conjuncao(verdadeiro,verdadeiro,verdadeiro).
conjuncao(verdadeiro,desconhecido,desconhecido).
conjuncao(desconhecido,verdadeiro,desconhecido).
conjuncao(desconhecido,desconhecido,desconhecido).
conjuncao(falso,_,falso).
conjuncao(_,falso,falso).

% Extensao do predicado disjuncao: X,Y -> {V,F,D}
disjuncao(verdadeiro,_,verdadeiro).
disjuncao(_,verdadeiro,verdadeiro).
disjuncao(falso,falso,falso).
disjuncao(falso,desconhecido,desconhecido).
disjuncao(desconhecido,falso,desconhecido).
disjuncao(desconhecido,desconhecido,desconhecido).
#+end_src

* Grupo 2

1. Na linguagem de programação em lógica PROLOG, a expressão 'A=..B' representa a comparação dos valores decimais de A e B.

   Falso, representa o funtor de um dado termo, colocando numa lista o nome do termo e os seus respetivos arguemtos.

   Exemplo:
  #+begin_src prolog
amigos(arroz,batata(2)) =.. L.
  #+end_src

  :Result:
  #+begin_src prolog
L = [amigos, arroz, batata(2)]
  #+end_src

1. Na linguagem de programação prolog, o operador '=:=/2' representa a comparação dos valores aritméticos calculados de cada operando.

   Verdadeiro. Em oposicao ao operador '==\2', o '=:=\2' calcula primeiro os valores aritmeticos e só depois compara o resultado obtido de ambos os lados.

   Exemplo:
  #+begin_src prolog
3 == 2 + 1.

Falso

3 =:= 2 + 1.

Verdadeiro
  #+end_src

2. 'negação forte' e 'negação explicta' são duas designações para identificar a negação por falha de prova.

   ???

   Falso, a 'negacao explicita' acontece por falha na prova, ja a 'negação forte' acontece devido a falha de predicados

3. Em termos da representação de conhecimento imperfeito, os valores nulos tanto podem assumir a representação de conhecimento positivo como de conhecimento negativo.

   Falso.

4. Invariantes denotam regras de teste à consistência do conhecimento, com os quais se representa conhecimento positivo ou conhecimento negativo.

   + Falso, porque os invariantes apenas servem para garantir que a base de conhecimento continua válida após a remoção ou adicição de um dado conhecimento.

* Grupo 3
1. Questão

   V, V, V, F, V.
