
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "DUMP id numComandos : Comandos ComandoComandos : ComandoComando : id '=' ExpComando : '!' ExpComando : '?' idComando : DUMPExp : Exp '+' TermoExp : Exp '-' TermoExp : TermoTermo : Termo '*' FatorTermo : Termo '/' FatorTermo : FatorFator : '(' Exp ')'Fator : numFator : id"
    
_lr_action_items = {'id':([0,1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,],[3,3,-2,14,15,-6,-1,14,-4,-9,-12,14,-14,-15,-5,-3,14,14,14,14,-7,-8,-10,-11,-13,]),'!':([0,1,2,6,7,9,10,11,13,14,15,16,22,23,24,25,26,],[4,4,-2,-6,-1,-4,-9,-12,-14,-15,-5,-3,-7,-8,-10,-11,-13,]),'?':([0,1,2,6,7,9,10,11,13,14,15,16,22,23,24,25,26,],[5,5,-2,-6,-1,-4,-9,-12,-14,-15,-5,-3,-7,-8,-10,-11,-13,]),'DUMP':([0,1,2,6,7,9,10,11,13,14,15,16,22,23,24,25,26,],[6,6,-2,-6,-1,-4,-9,-12,-14,-15,-5,-3,-7,-8,-10,-11,-13,]),'$end':([1,2,6,7,9,10,11,13,14,15,16,22,23,24,25,26,],[0,-2,-6,-1,-4,-9,-12,-14,-15,-5,-3,-7,-8,-10,-11,-13,]),'=':([3,],[8,]),'(':([4,8,12,17,18,19,20,],[12,12,12,12,12,12,12,]),'num':([4,8,12,17,18,19,20,],[13,13,13,13,13,13,13,]),'+':([9,10,11,13,14,16,21,22,23,24,25,26,],[17,-9,-12,-14,-15,17,17,-7,-8,-10,-11,-13,]),'-':([9,10,11,13,14,16,21,22,23,24,25,26,],[18,-9,-12,-14,-15,18,18,-7,-8,-10,-11,-13,]),')':([10,11,13,14,21,22,23,24,25,26,],[-9,-12,-14,-15,26,-7,-8,-10,-11,-13,]),'*':([10,11,13,14,22,23,24,25,26,],[19,-12,-14,-15,19,19,-10,-11,-13,]),'/':([10,11,13,14,22,23,24,25,26,],[20,-12,-14,-15,20,20,-10,-11,-13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Comandos':([0,],[1,]),'Comando':([0,1,],[2,7,]),'Exp':([4,8,12,],[9,16,21,]),'Termo':([4,8,12,17,18,],[10,10,10,22,23,]),'Fator':([4,8,12,17,18,19,20,],[11,11,11,11,11,24,25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Comandos","S'",1,None,None,None),
  ('Comandos -> Comandos Comando','Comandos',2,'p_Comandos_Lista','calc_sin.py',6),
  ('Comandos -> Comando','Comandos',1,'p_Comandos_Simples','calc_sin.py',9),
  ('Comando -> id = Exp','Comando',3,'p_Comandos_Atrib','calc_sin.py',12),
  ('Comando -> ! Exp','Comando',2,'p_Comandos_Escrita','calc_sin.py',16),
  ('Comando -> ? id','Comando',2,'p_Comandos_Leitura','calc_sin.py',20),
  ('Comando -> DUMP','Comando',1,'p_Comandos_Dump','calc_sin.py',25),
  ('Exp -> Exp + Termo','Exp',3,'p_Exp_add','calc_sin.py',29),
  ('Exp -> Exp - Termo','Exp',3,'p_Exp_sub','calc_sin.py',33),
  ('Exp -> Termo','Exp',1,'p_Exp_Termo','calc_sin.py',37),
  ('Termo -> Termo * Fator','Termo',3,'p_Termo_mul','calc_sin.py',41),
  ('Termo -> Termo / Fator','Termo',3,'p_Termo_div','calc_sin.py',45),
  ('Termo -> Fator','Termo',1,'p_Termo_Fator','calc_sin.py',52),
  ('Fator -> ( Exp )','Fator',3,'p_Fator_grupo','calc_sin.py',56),
  ('Fator -> num','Fator',1,'p_Fator_num','calc_sin.py',60),
  ('Fator -> id','Fator',1,'p_Fator_id','calc_sin.py',64),
]
